image: ubuntu

before_build:
- sudo apt-get update
- sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
- sudo apt-get install libxml2-dev

build_script:
- mkdir -p build
- cd build
- cmake ..
- make
