before_install:
- sudo apt-get update
- sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
- sudo apt-get install -y libxml2-dev
- git submodule update --init --recursive

jobs:
  include:
    - stage: build
    - mkdir -p build
    - cd build
    - cmake ..
    - make
